export enum RouteName {
  Home = 'home',
  Profiles = 'profiles',
  Profile = 'profile',
  Categories = 'categories',
  Category = 'category',
  Movies = 'movies',
  Movie = 'movie',
  Stars = 'stars',
  Star = 'star',
  Websites = 'websites',
  Website = 'website',
  Tags = 'tags',
  Tag = 'tag',
  InProgress = 'in-progress',
  ToSee = 'to-see',
  PotentialBest = 'potential-best',
  Best = 'best',
  AbsoluteBest = 'absolute-best',
  ToTag = 'to-tag',
  Commented = 'commented',
  ToFollow = 'to-follow',
}
